import Head from 'next/head';
import Image from 'next/image';
import Car from '../../public/Car.svg';
import styles from '../styles/Home.module.scss';
import { CarComponent } from '../components/CarComponent';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className={styles.container}>
        <Image src={Car} alt='Frame' />
        <h1>FEATURED CARS</h1>
        <div>
          <CarComponent />
          <CarComponent />
          <CarComponent />
          <CarComponent />
          <CarComponent />
          <CarComponent />
          <CarComponent />
          <CarComponent />
        </div>
      </section>
    </>
  );
}
